---

name: Add Repo Issue to ALD GH project
on:
  issues:
    types:
      - opened
      - reopened
      - transferred
jobs:
  add-to-project:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1.0.2
        with:
          project-url: https://github.com/orgs/ansible-lockdown/projects/1
          github-token: ${{ secrets.GITHUB_TOKEN }}
